# Generated by Django 2.2.24 on 2025-06-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_auto_20250618_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='next_evolutions',
        ),
    ]
