# Generated by Django 2.2.24 on 2025-07-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_remove_pokemon_next_evolutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_name', to='pokemon_entities.Pokemon', verbose_name='Название покемона'),
        ),
    ]
